export const non_target_images = [
  { index: 0,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\brooke-cagle--uHVRvDr7pg-unsplash.jpg") },
    { index: 1,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\brooke-cagle-g1Kr4Ozfoac-unsplash.jpg") },
    { index: 2,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\elevate-nYgy58eb9aw-unsplash.jpg") },
    { index: 3,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-alex-green-5699500.jpg") },
    { index: 4,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-alexander-suhorucov-6457488.jpg") },
    { index: 5,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-alexander-suhorucov-6457512.jpg") },
    { index: 6,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-alexander-suhorucov-6457544.jpg") },
    { index: 7,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-allan-mas-5368956.jpg") },
    { index: 8,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-amina-filkins-5413724.jpg") },
    { index: 9,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-anastasia-shuraeva-7279710.jpg") },
    { index: 10,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-andrea-piacquadio-3764551.jpg") },
    { index: 11,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-andrea-piacquadio-3765046.jpg") },
    { index: 12,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-andrea-piacquadio-3768146.jpg") },
    { index: 13,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-andrea-piacquadio-3940481.jpg") },
    { index: 14,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-andrea-piacquadio-866023.jpg") },
    { index: 15,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-anna-shvets-5257303.jpg") },
    { index: 16,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-armin-rimoldi-5553106.jpg") },
    { index: 17,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-armin-rimoldi-5554256.jpg") },
    { index: 18,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-artem-podrez-4816756.jpg") },
    { index: 19,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-askar-abayev-5638676.jpg") },
    { index: 20,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-august-de-richelieu-4262009.jpg") },
    { index: 21,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-august-de-richelieu-4427626.jpg") },
    { index: 22,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-blue-bird-7218670.jpg") },
    { index: 23,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-brett-sayles-1303753.jpg") },
    { index: 24,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-budgeron-bach-5157196.jpg") },
    { index: 25,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-budgeron-bach-6532612.jpg") },
    { index: 26,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-cedric-fauntleroy-7220318.jpg") },
    { index: 27,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-charlotte-may-5965685.jpg") },
    { index: 28,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-christina-morillo-1181273.jpg") },
    { index: 29,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-christina-morillo-1181432.jpg") },
    { index: 30,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-cliff-booth-4057863.jpg") },
    { index: 31,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-cottonbro-4004461.jpg") },
    { index: 32,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-cottonbro-4101143.jpg") },
    { index: 33,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-cottonbro-4684249.jpg") },
    { index: 34,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-cottonbro-4911748.jpg") },
    { index: 35,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-cottonbro-5020303.jpg") },
    { index: 36,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-cottonbro-6954063.jpg") },
    { index: 37,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-cottonbro-9154876.jpg") },
    { index: 38,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-cottonbro-9722008.jpg") },
    { index: 39,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-darlene-alderson-7971198.jpg") },
    { index: 40,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-edmond-dantès-4339794.jpg") },
    { index: 41,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-edmond-dantès-8555530.jpg") },
    { index: 42,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-ekaterina-bolovtsova-4049987.jpg") },
    { index: 43,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-ekaterina-bolovtsova-4051134.jpg") },
    { index: 44,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-elevate-1267694.jpg") },
    { index: 45,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-fauxels-3182798.jpg") },
    { index: 46,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-fauxels-3184177.jpg") },
    { index: 47,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-fauxels-3184407.jpg") },
    { index: 48,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-gary-barnes-6231588.jpg") },
    { index: 49,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-george-milton-6954031.jpg") },
    { index: 50,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-george-milton-6954199.jpg") },
    { index: 51,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-george-pak-7972671.jpg") },
    { index: 52,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-george-pak-7973205.jpg") },
    { index: 53,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-gustavo-fring-4920512.jpg") },
    { index: 54,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-gustavo-fring-8769358.jpg") },
    { index: 55,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-inga-seliverstova-3394229.jpg") },
    { index: 56,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-inga-seliverstova-3394230.jpg") },
    { index: 57,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-ivan-samkov-8117415.jpg") },
    { index: 58,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-john-diez-7388882.jpg") },
    { index: 59,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-karolina-grabowska-6255919.jpg") },
    { index: 60,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-keira-burton-6147065.jpg") },
    { index: 61,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-keira-burton-6147409.jpg") },
    { index: 62,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-ketut-subiyanto-4132440.jpg") },
    { index: 63,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-ketut-subiyanto-4623334.jpg") },
    { index: 64,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-ketut-subiyanto-5038813.jpg") },
    { index: 65,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-kevin-malik-8763231.jpg") },
    { index: 66,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-kindel-media-7149019.jpg") },
    { index: 67,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-kindel-media-7149135.jpg") },
    { index: 68,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-kindel-media-7293994.jpg") },
    { index: 69,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-kindel-media-7651978.jpg") },
    { index: 70,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-kindel-media-7935669.jpg") },
    { index: 71,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-marcus-aurelius-4063788.jpg") },
    { index: 72,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-mart-production-7643868.jpg") },
    { index: 73,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-mart-production-8121702.jpg") },
    { index: 74,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-martin-lopez-2240763.jpg") },
    { index: 75,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-mary-taylor-5896589.jpg") },
    { index: 76,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-matheus-bertelli-13832974.jpg") },
    { index: 77,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-mikhail-nilov-7777664.jpg") },
    { index: 78,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-mikhail-nilov-7988689.jpg") },
    { index: 79,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-mikhail-nilov-8669812.jpg") },
    { index: 80,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-monstera-5384438.jpg") },
    { index: 81,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-monstera-5384447.jpg") },
    { index: 82,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-monstera-6238045.jpg") },
    { index: 83,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-monstera-6238046.jpg") },
    { index: 84,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-monstera-6238226.jpg") },
    { index: 85,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-norma-mortenson-4393665.jpg") },
    { index: 86,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-olia-danilevich-5729071.jpg") },
    { index: 87,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-pavel-danilyuk-7776097.jpg") },
    { index: 88,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-rodnae-productions-5837019.jpg") },
    { index: 89,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-rodnae-productions-7683744.jpg") },
    { index: 90,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-ron-lach-10020185.jpg") },
    { index: 91,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-sam-lion-5709268.jpg") },
    { index: 92,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-sarah-chai-7267472.jpg") },
    { index: 93,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-shvets-production-7176223.jpg") },
    { index: 94,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-sora-shimazaki-5668459.jpg") },
    { index: 95,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-sora-shimazaki-5668857.jpg") },
    { index: 96,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-steshka-willems-2981571.jpg") },
    { index: 97,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-thiago-miranda-1230396.jpg") },
    { index: 98,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-thirdman-7219113.jpg") },
    { index: 99,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-thirdman-8920727.jpg") },
    { index: 100,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-thisisengineering-3862135.jpg") },
    { index: 101,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-tim-douglas-6205746.jpg") },
    { index: 102,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-tim-douglas-6567352.jpg") },
    { index: 103,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-tirachard-kumtanom-601170.jpg") },
    { index: 104,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-trung-nguyen-3571377.jpg") },
    { index: 105,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-uriel-mont-6314965.jpg") },
    { index: 106,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-werner-pfennig-6950095.jpg") },
    { index: 107,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-william-fortunato-6140414.jpg") },
    { index: 108,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-william-fortunato-6140463.jpg") },
    { index: 109,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-william-fortunato-6140678.jpg") },
    { index: 110,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-william-fortunato-6140707.jpg") },
    { index: 111,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-yan-krukov-8911776.jpg") },
    { index: 112,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-yaroslav-shuraev-6185162.jpg") },
    { index: 113,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-yaroslav-shuraev-8514598.jpg") },
    { index: 114,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-yaroslav-shuraev-8515123.jpg") },
    { index: 115,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-zen-chung-5537997.jpg") },
    { index: 116,
    category: "non-target",
    image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\non-target\\pexels-zen-chung-5538594.jpg") 
    },
  ];
  export const target_images = [
    { index: 0,
      category: "target",
      image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\target-photo\\F1.jpg") },
      { index: 1,
      category: "target",
      image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\target-photo\\F10.jpg") },
      { index: 2,
      category: "target",
      image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\target-photo\\F11.jpg") },
      { index: 3,
      category: "target",
      image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\target-photo\\F12.jpg") },
      { index: 4,
      category: "target",
      image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\target-photo\\F13.jpg") },
      { index: 5,
      category: "target",
      image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\target-photo\\F14.jpg") },
      { index: 6,
      category: "target",
      image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\target-photo\\F15.jpg") },
      { index: 7,
      category: "target",
      image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\target-photo\\F16.jpg") },
      { index: 8,
      category: "target",
      image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\target-photo\\F17.jpg") },
      { index: 9,
      category: "target",
      image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\target-photo\\F19.jpg") },
      { index: 10,
      category: "target",
      image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\target-photo\\F1a.jpg") },
      { index: 11,
      category: "target",
      image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\target-photo\\F2.jpg") },
      { index: 12,
      category: "target",
      image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\target-photo\\F20.jpg") },
      { index: 13,
      category: "target",
      image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\target-photo\\F3.jpg") },
      { index: 14,
      category: "target",
      image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\target-photo\\F4.jpg") },
      { index: 15,
      category: "target",
      image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\target-photo\\F5.jpg") },
      { index: 16,
      category: "target",
      image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\target-photo\\F6.jpg") },
      { index: 17,
      category: "target",
      image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\target-photo\\F7.jpg") },
      { index: 18,
      category: "target",
      image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\target-photo\\F8.jpg") },
      { index: 19,
      category: "target",
      image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\target-photo\\F9.jpg") 
      },
    ];
