export const target_images = [
  {'index': 0, category: 'target', 'image': require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\1\\T1_01.jpg")},
  {'index': 1, 'category': 'target', 'image': require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\2\\T2_01.jpg")},
  {'index': 2, 'category': 'target', 'image': require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\3\\T3_01.jpg")},
  {'index': 3, 'category': 'target', 'image': require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\12\\T12_01.jpg")},
  {'index': 4, 'category': 'target', 'image': require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\13\\T13_01.jpg")},
  {'index': 5, 'category': 'target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\2\\T2_01.jpg")'},
  {'index': 6, 'category': 'target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\3\\T3_01.jpg")'},
  {'index': 7, 'category': 'target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\T4_01.jpg")'},
  {'index': 8, 'category': 'target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\T5_01.jpg")'},
  {'index': 9, 'category': 'target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\T6_01.jpg")'},
  {'index': 10, 'category': 'target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\T7_01.jpg")'},
  {'index': 11, 'category': 'target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\T8_01.jpg")'},
  {'index': 12, 'category': 'target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\T9_01.jpg")'},
]

// 'image': require(C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\2\\T2_01.jpg)
// 'image': require(C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\3\\T3_01.jpg)
// 'image': require(C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\T4_01.jpg)
// 'image': require(C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\T5_01.jpg)
// 'image': require(C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\T6_01.jpg)
// 'image': require(C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\T7_01.jpg)
// 'image': require(C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\T8_01.jpg)
// 'image': require(C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\T9_01.jpg)


export const non_target_images = [
  {'index':0,  category: 'non-target', image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\1\\C1_01.jpg")},
  {'index': 1, 'category': 'non-target', 'image': require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\1\\C1_02.jpg")},
  {'index': 2, 'category': 'non-target', image: require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\1\\C1_03.jpg")},
  {'index': 3, 'category': 'non-target', 'image': require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\1\\C1_04.jpg")},
  {'index': 4, 'category': 'non-target', 'image': require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\1\\C1_05.jpg")},
  {'index': 5, 'category': 'non-target', 'image': require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\1\\C1_06.jpg")},
  {'index': 6, 'category': 'non-target', 'image': require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\1\\C1_07.jpg")},
  {'index': 7, 'category': 'non-target', 'image': require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\1\\C1_08.jpg")},
  {'index': 8, 'category': 'non-target', 'image': require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\2\\C2_01.jpg")},
  {'index': 9, 'category': 'non-target', 'image': require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\2\\C2_02.jpg")},
  {'index': 10, 'category': 'non-target', 'image': require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\2\\C2_03.jpg")},
  {'index': 11, 'category': 'non-target', 'image': require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\2\\C2_04.jpg")},
  {'index': 12, 'category': 'non-target', 'image': require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\2\\C2_05.jpg")},
  {'index': 13, 'category': 'non-target', 'image': require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\2\\C2_06.jpg")},
  {'index': 14, 'category': 'non-target', 'image': require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\2\\C2_07.jpg")},
  {'index': 15, 'category': 'non-target', 'image': require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\2\\C2_08.jpg")},
  {'index': 16, 'category': 'non-target', 'image':  require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\3\\C3_01.jpg")},
  {'index': 17, 'category': 'non-target', 'image': require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\3\\C3_02.jpg")},
  {'index': 18, 'category': 'non-target', 'image': require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\3\\C3_03.jpg")},
  {'index': 19, 'category': 'non-target', 'image': require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\3\\C3_04.jpg")} ,
  {'index': 20, 'category': 'non-target', 'image': require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\3\\C3_05.jpg")},
  {'index': 21, 'category': 'non-target', 'image': require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\3\\C3_06.jpg")},
  {'index': 22, 'category': 'non-target', 'image': require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\3\\C3_07.jpg")},
  {'index': 23, 'category': 'non-target', 'image': require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\3\\C3_08.jpg")},
]








// export const non_target_images = [
//   {'index': 0, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\1\\C1_01.jpg")'},
//   {'index': 1, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\1\\C1_02.jpg")'},
//   {'index': 2, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\1\\C1_03.jpg")'},
//   {'index': 3, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\1\\C1_04.jpg")'},
//   {'index': 4, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\1\\C1_05.jpg")'},
//   {'index': 5, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\1\\C1_06.jpg")'},
//   {'index': 6, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\1\\C1_07.jpg")'},
//   {'index': 7, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\1\\C1_08.jpg")'},
//   {'index': 8, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\10\\C10_01.jpg")'},
//   {'index': 9, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\10\\C10_02.jpg")'},
//   {'index': 10, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\10\\C10_03.jpg")'},
//   {'index': 11, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\10\\C10_04.jpg")'},
//   {'index': 12, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\10\\C10_05.jpg")'},
//   {'index': 13, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\10\\C10_06.jpg")'},
//   {'index': 14, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\10\\C10_07.jpg")'},
//   {'index': 15, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\10\\C10_08.jpg")'},
//   {'index': 16, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\10\\C10_09.jpg")'},
//   {'index': 17, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\10\\C10_10.jpg")'},
//   {'index': 18, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\10\\C10_11.jpg")'},
//   {'index': 19, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\10\\C10_12.jpg")'},
//   {'index': 20, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\10\\C10_13.jpg")'},
//   {'index': 21, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\10\\C10_14.jpg")'},
//   {'index': 22, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\10\\C10_15.jpg")'},
//   {'index': 23, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\10\\C10_16.jpg")'},
//   {'index': 24, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\10\\C10_17.jpg")'},
//   {'index': 25, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\10\\C10_18.jpg")'},
//   {'index': 26, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\10\\C10_19.jpg")'},
//   {'index': 27, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\10\\C10_20.jpg")'},
//   {'index': 28, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\10\\C10_21.jpg")'},
//   {'index': 29, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\10\\C10_22.jpg")'},
//   {'index': 30, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\10\\C10_23.jpg")'},
//   {'index': 31, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\10\\C10_24.jpg")'},
//   {'index': 32, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\10\\C10_25.jpg")'},
//   {'index': 33, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\10\\C10_26.jpg")'},
//   {'index': 34, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\10\\C10_27.jpg")'},
//   {'index': 35, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\10\\C10_28.jpg")'},
//   {'index': 36, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\10\\C10_29.jpg")'},
//   {'index': 37, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\10\\C10_30.jpg")'},
//   {'index': 38, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\10\\C10_31.jpg")'},
//   {'index': 39, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\10\\C10_32.jpg")'},
//   {'index': 40, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\10\\C10_33.jpg")'},
//   {'index': 41, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\10\\C10_34.jpg")'},
//   {'index': 42, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\10\\C10_35.jpg")'},
//   {'index': 43, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\11\\C11_01.jpg")'},
//   {'index': 44, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\11\\C11_02.jpg")'},
//   {'index': 45, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\11\\C11_03.jpg")'},
//   {'index': 46, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\11\\C11_04.jpg")'},
//   {'index': 47, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\11\\C11_05.jpg")'},
//   {'index': 48, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\11\\C11_06.jpg")'},
//   {'index': 49, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\11\\C11_07.jpg")'},
//   {'index': 50, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\11\\C11_08.jpg")'},
//   {'index': 51, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\11\\C11_09.jpg")'},
//   {'index': 52, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\11\\C11_10.jpg")'},
//   {'index': 53, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\11\\C11_11.jpg")'},
//   {'index': 54, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\11\\C11_12.jpg")'},
//   {'index': 55, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\11\\C11_13.jpg")'},
//   {'index': 56, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\11\\C11_14.jpg")'},
//   {'index': 57, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\11\\C11_15.jpg")'},
//   {'index': 58, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\11\\C11_16.jpg")'},
//   {'index': 59, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\11\\C11_17.jpg")'},
//   {'index': 60, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\11\\C11_18.jpg")'},
//   {'index': 61, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\11\\C11_19.jpg")'},
//   {'index': 62, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\11\\C11_20.jpg")'},
//   {'index': 63, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\11\\C11_21.jpg")'},
//   {'index': 64, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\11\\C11_22.jpg")'},
//   {'index': 65, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\11\\C11_23.jpg")'},
//   {'index': 66, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\11\\C11_24.jpg")'},
//   {'index': 67, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\11\\C11_25.jpg")'},
//   {'index': 68, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\11\\C11_26.jpg")'},
//   {'index': 69, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\11\\C11_27.jpg")'},
//   {'index': 70, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\11\\C11_28.jpg")'},
//   {'index': 71, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\11\\C11_29.jpg")'},
//   {'index': 72, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\11\\C11_30.jpg")'},
//   {'index': 73, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\11\\C11_31.jpg")'},
//   {'index': 74, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\11\\C11_32.jpg")'},
//   {'index': 75, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\11\\C11_33.jpg")'},
//   {'index': 76, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\11\\C11_34.jpg")'},
//   {'index': 77, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\11\\C11_35.jpg")'},
//   {'index': 78, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\12\\C12_01.jpg")'},
//   {'index': 79, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\12\\C12_02.jpg")'},
//   {'index': 80, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\12\\C12_03.jpg")'},
//   {'index': 81, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\12\\C12_04.jpg")'},
//   {'index': 82, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\12\\C12_05.jpg")'},
//   {'index': 83, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\12\\C12_06.jpg")'},
//   {'index': 84, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\12\\C12_07.jpg")'},
//   {'index': 85, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\12\\C12_08.jpg")'},
//   {'index': 86, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\12\\C12_09.jpg")'},
//   {'index': 87, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\12\\C12_10.jpg")'},
//   {'index': 88, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\12\\C12_11.jpg")'},
//   {'index': 89, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\12\\C12_12.jpg")'},
//   {'index': 90, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\12\\C12_13.jpg")'},
//   {'index': 91, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\12\\C12_14.jpg")'},
//   {'index': 92, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\12\\C12_15.jpg")'},
//   {'index': 93, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\12\\C12_16.jpg")'},
//   {'index': 94, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\12\\C12_17.jpg")'},
//   {'index': 95, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\12\\C12_18.jpg")'},
//   {'index': 96, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\12\\C12_19.jpg")'},
//   {'index': 97, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\12\\C12_20.jpg")'},
//   {'index': 98, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\12\\C12_21.jpg")'},
//   {'index': 99, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\12\\C12_22.jpg")'},
//   {'index': 100, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\12\\C12_23.jpg")'},
//   {'index': 101, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\12\\C12_24.jpg")'},
//   {'index': 102, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\12\\C12_25.jpg")'},
//   {'index': 103, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\12\\C12_26.jpg")'},
//   {'index': 104, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\12\\C12_27.jpg")'},
//   {'index': 105, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\12\\C12_28.jpg")'},
//   {'index': 106, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\12\\C12_29.jpg")'},
//   {'index': 107, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\12\\C12_30.jpg")'},
//   {'index': 108, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\12\\C12_31.jpg")'},
//   {'index': 109, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\12\\C12_32.jpg")'},
//   {'index': 110, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\12\\C12_33.jpg")'},
//   {'index': 111, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\12\\C12_34.jpg")'},
//   {'index': 112, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\12\\C12_35.jpg")'},
//   {'index': 113, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\13\\C13_01.jpg")'},
//   {'index': 114, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\13\\C13_02.jpg")'},
//   {'index': 115, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\13\\C13_03.jpg")'},
//   {'index': 116, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\13\\C13_04.jpg")'},
//   {'index': 117, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\13\\C13_05.jpg")'},
//   {'index': 118, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\13\\C13_06.jpg")'},
//   {'index': 119, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\13\\C13_07.jpg")'},
//   {'index': 120, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\13\\C13_08.jpg")'},
//   {'index': 121, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\13\\C13_09.jpg")'},
//   {'index': 122, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\13\\C13_10.jpg")'},
//   {'index': 123, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\13\\C13_11.jpg")'},
//   {'index': 124, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\13\\C13_12.jpg")'},
//   {'index': 125, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\13\\C13_13.jpg")'},
//   {'index': 126, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\13\\C13_14.jpg")'},
//   {'index': 127, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\13\\C13_15.jpg")'},
//   {'index': 128, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\13\\C13_16.jpg")'},
//   {'index': 129, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\13\\C13_17.jpg")'},
//   {'index': 130, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\13\\C13_18.jpg")'},
//   {'index': 131, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\13\\C13_19.jpg")'},
//   {'index': 132, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\13\\C13_20.jpg")'},
//   {'index': 133, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\13\\C13_21.jpg")'},
//   {'index': 134, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\13\\C13_22.jpg")'},
//   {'index': 135, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\13\\C13_23.jpg")'},
//   {'index': 136, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\13\\C13_24.jpg")'},
//   {'index': 137, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\13\\C13_25.jpg")'},
//   {'index': 138, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\13\\C13_26.jpg")'},
//   {'index': 139, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\13\\C13_27.jpg")'},
//   {'index': 140, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\13\\C13_28.jpg")'},
//   {'index': 141, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\13\\C13_29.jpg")'},
//   {'index': 142, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\13\\C13_30.jpg")'},
//   {'index': 143, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\13\\C13_31.jpg")'},
//   {'index': 144, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\13\\C13_32.jpg")'},
//   {'index': 145, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\13\\C13_33.jpg")'},
//   {'index': 146, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\13\\C13_34.jpg")'},
//   {'index': 147, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\13\\C13_35.jpg")'},
//   {'index': 148, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\2\\C2_01.jpg")'},
//   {'index': 149, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\2\\C2_02.jpg")'},
//   {'index': 150, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\2\\C2_03.jpg")'},
//   {'index': 151, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\2\\C2_04.jpg")'},
//   {'index': 152, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\2\\C2_05.jpg")'},
//   {'index': 153, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\2\\C2_06.jpg")'},
//   {'index': 154, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\2\\C2_07.jpg")'},
//   {'index': 155, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\2\\C2_08.jpg")'},
//   {'index': 156, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\3\\C3_01.jpg")'},
//   {'index': 157, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\3\\C3_02.jpg")'},
//   {'index': 158, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\3\\C3_03.jpg")'},
//   {'index': 159, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\3\\C3_04.jpg")'},
//   {'index': 160, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\3\\C3_05.jpg")'},
//   {'index': 161, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\3\\C3_06.jpg")'},
//   {'index': 162, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\3\\C3_07.jpg")'},
//   {'index': 163, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\3\\C3_08.jpg")'},
//   {'index': 164, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\C4_01.jpg")'},
//   {'index': 165, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\C4_02.jpg")'},
//   {'index': 166, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\C4_03.jpg")'},
//   {'index': 167, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\C4_04.jpg")'},
//   {'index': 168, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\C4_05.jpg")'},
//   {'index': 169, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\C4_06.jpg")'},
//   {'index': 170, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\C4_07.jpg")'},
//   {'index': 171, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\C4_08.jpg")'},
//   {'index': 172, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\C4_09.jpg")'},
//   {'index': 173, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\C4_10.jpg")'},
//   {'index': 174, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\C4_11.jpg")'},
//   {'index': 175, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\C4_12.jpg")'},
//   {'index': 176, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\C4_13.jpg")'},
//   {'index': 177, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\C4_14.jpg")'},
//   {'index': 178, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\C4_15.jpg")'},
//   {'index': 179, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\C4_16.jpg")'},
//   {'index': 180, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\C4_17.jpg")'},
//   {'index': 181, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\C4_18.jpg")'},
//   {'index': 182, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\C4_19.jpg")'},
//   {'index': 183, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\C4_20.jpg")'},
//   {'index': 184, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\C4_21.jpg")'},
//   {'index': 185, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\C4_22.jpg")'},
//   {'index': 186, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\C4_23.jpg")'},
//   {'index': 187, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\C4_24.jpg")'},
//   {'index': 188, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\C4_25.jpg")'},
//   {'index': 189, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\C4_26.jpg")'},
//   {'index': 190, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\C4_27.jpg")'},
//   {'index': 191, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\C4_28.jpg")'},
//   {'index': 192, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\C4_29.jpg")'},
//   {'index': 193, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\C4_30.jpg")'},
//   {'index': 194, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\C4_31.jpg")'},
//   {'index': 195, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\C4_32.jpg")'},
//   {'index': 196, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\C4_33.jpg")'},
//   {'index': 197, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\C4_34.jpg")'},
//   {'index': 198, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\4\\C4_35.jpg")'},
//   {'index': 199, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\C5_01.jpg")'},
//   {'index': 200, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\C5_02.jpg")'},
//   {'index': 201, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\C5_03.jpg")'},
//   {'index': 202, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\C5_04.jpg")'},
//   {'index': 203, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\C5_05.jpg")'},
//   {'index': 204, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\C5_06.jpg")'},
//   {'index': 205, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\C5_07.jpg")'},
//   {'index': 206, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\C5_08.jpg")'},
//   {'index': 207, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\C5_09.jpg")'},
//   {'index': 208, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\C5_10.jpg")'},
//   {'index': 209, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\C5_11.jpg")'},
//   {'index': 210, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\C5_12.jpg")'},
//   {'index': 211, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\C5_13.jpg")'},
//   {'index': 212, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\C5_14.jpg")'},
//   {'index': 213, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\C5_15.jpg")'},
//   {'index': 214, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\C5_16.jpg")'},
//   {'index': 215, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\C5_17.jpg")'},
//   {'index': 216, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\C5_18.jpg")'},
//   {'index': 217, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\C5_19.jpg")'},
//   {'index': 218, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\C5_20.jpg")'},
//   {'index': 219, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\C5_21.jpg")'},
//   {'index': 220, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\C5_22.jpg")'},
//   {'index': 221, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\C5_23.jpg")'},
//   {'index': 222, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\C5_24.jpg")'},
//   {'index': 223, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\C5_25.jpg")'},
//   {'index': 224, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\C5_26.jpg")'},
//   {'index': 225, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\C5_27.jpg")'},
//   {'index': 226, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\C5_28.jpg")'},
//   {'index': 227, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\C5_29.jpg")'},
//   {'index': 228, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\C5_30.jpg")'},
//   {'index': 229, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\C5_31.jpg")'},
//   {'index': 230, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\C5_32.jpg")'},
//   {'index': 231, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\C5_33.jpg")'},
//   {'index': 232, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\C5_34.jpg")'},
//   {'index': 233, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\5\\C5_35.jpg")'},
//   {'index': 234, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\C6_01.jpg")'},
//   {'index': 235, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\C6_02.jpg")'},
//   {'index': 236, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\C6_03.jpg")'},
//   {'index': 237, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\C6_04.jpg")'},
//   {'index': 238, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\C6_05.jpg")'},
//   {'index': 239, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\C6_06.jpg")'},
//   {'index': 240, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\C6_07.jpg")'},
//   {'index': 241, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\C6_08.jpg")'},
//   {'index': 242, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\C6_09.jpg")'},
//   {'index': 243, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\C6_10.jpg")'},
//   {'index': 244, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\C6_11.jpg")'},
//   {'index': 245, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\C6_12.jpg")'},
//   {'index': 246, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\C6_13.jpg")'},
//   {'index': 247, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\C6_14.jpg")'},
//   {'index': 248, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\C6_15.jpg")'},
//   {'index': 249, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\C6_16.jpg")'},
//   {'index': 250, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\C6_17.jpg")'},
//   {'index': 251, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\C6_18.jpg")'},
//   {'index': 252, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\C6_19.jpg")'},
//   {'index': 253, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\C6_20.jpg")'},
//   {'index': 254, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\C6_21.jpg")'},
//   {'index': 255, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\C6_22.jpg")'},
//   {'index': 256, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\C6_23.jpg")'},
//   {'index': 257, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\C6_24.jpg")'},
//   {'index': 258, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\C6_25.jpg")'},
//   {'index': 259, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\C6_26.jpg")'},
//   {'index': 260, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\C6_27.jpg")'},
//   {'index': 261, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\C6_28.jpg")'},
//   {'index': 262, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\C6_29.jpg")'},
//   {'index': 263, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\C6_30.jpg")'},
//   {'index': 264, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\C6_31.jpg")'},
//   {'index': 265, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\C6_32.jpg")'},
//   {'index': 266, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\C6_33.jpg")'},
//   {'index': 267, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\C6_34.jpg")'},
//   {'index': 268, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\6\\C6_35.jpg")'},
//   {'index': 269, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\C7_01.jpg")'},
//   {'index': 270, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\C7_02.jpg")'},
//   {'index': 271, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\C7_03.jpg")'},
//   {'index': 272, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\C7_04.jpg")'},
//   {'index': 273, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\C7_05.jpg")'},
//   {'index': 274, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\C7_06.jpg")'},
//   {'index': 275, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\C7_07.jpg")'},
//   {'index': 276, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\C7_08.jpg")'},
//   {'index': 277, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\C7_09.jpg")'},
//   {'index': 278, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\C7_10.jpg")'},
//   {'index': 279, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\C7_11.jpg")'},
//   {'index': 280, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\C7_12.jpg")'},
//   {'index': 281, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\C7_13.jpg")'},
//   {'index': 282, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\C7_14.jpg")'},
//   {'index': 283, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\C7_15.jpg")'},
//   {'index': 284, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\C7_16.jpg")'},
//   {'index': 285, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\C7_17.jpg")'},
//   {'index': 286, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\C7_18.jpg")'},
//   {'index': 287, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\C7_19.jpg")'},
//   {'index': 288, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\C7_20.jpg")'},
//   {'index': 289, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\C7_21.jpg")'},
//   {'index': 290, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\C7_22.jpg")'},
//   {'index': 291, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\C7_23.jpg")'},
//   {'index': 292, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\C7_24.jpg")'},
//   {'index': 293, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\C7_25.jpg")'},
//   {'index': 294, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\C7_26.jpg")'},
//   {'index': 295, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\C7_27.jpg")'},
//   {'index': 296, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\C7_28.jpg")'},
//   {'index': 297, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\C7_29.jpg")'},
//   {'index': 298, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\C7_30.jpg")'},
//   {'index': 299, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\C7_31.jpg")'},
//   {'index': 300, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\C7_32.jpg")'},
//   {'index': 301, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\C7_33.jpg")'},
//   {'index': 302, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\C7_34.jpg")'},
//   {'index': 303, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\7\\C7_35.jpg")'},
//   {'index': 304, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\C8_01.jpg")'},
//   {'index': 305, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\C8_02.jpg")'},
//   {'index': 306, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\C8_03.jpg")'},
//   {'index': 307, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\C8_04.jpg")'},
//   {'index': 308, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\C8_05.jpg")'},
//   {'index': 309, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\C8_06.jpg")'},
//   {'index': 310, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\C8_07.jpg")'},
//   {'index': 311, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\C8_08.jpg")'},
//   {'index': 312, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\C8_09.jpg")'},
//   {'index': 313, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\C8_10.jpg")'},
//   {'index': 314, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\C8_11.jpg")'},
//   {'index': 315, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\C8_12.jpg")'},
//   {'index': 316, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\C8_13.jpg")'},
//   {'index': 317, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\C8_14.jpg")'},
//   {'index': 318, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\C8_15.jpg")'},
//   {'index': 319, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\C8_16.jpg")'},
//   {'index': 320, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\C8_17.jpg")'},
//   {'index': 321, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\C8_18.jpg")'},
//   {'index': 322, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\C8_19.jpg")'},
//   {'index': 323, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\C8_20.jpg")'},
//   {'index': 324, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\C8_21.jpg")'},
//   {'index': 325, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\C8_22.jpg")'},
//   {'index': 326, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\C8_23.jpg")'},
//   {'index': 327, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\C8_24.jpg")'},
//   {'index': 328, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\C8_25.jpg")'},
//   {'index': 329, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\C8_26.jpg")'},
//   {'index': 330, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\C8_27.jpg")'},
//   {'index': 331, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\C8_28.jpg")'},
//   {'index': 332, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\C8_29.jpg")'},
//   {'index': 333, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\C8_30.jpg")'},
//   {'index': 334, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\C8_31.jpg")'},
//   {'index': 335, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\C8_32.jpg")'},
//   {'index': 336, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\C8_33.jpg")'},
//   {'index': 337, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\C8_34.jpg")'},
//   {'index': 338, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\8\\C8_35.jpg")'},
//   {'index': 339, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\C9_01.jpg")'},
//   {'index': 340, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\C9_02.jpg")'},
//   {'index': 341, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\C9_03.jpg")'},
//   {'index': 342, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\C9_04.jpg")'},
//   {'index': 343, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\C9_05.jpg")'},
//   {'index': 344, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\C9_06.jpg")'},
//   {'index': 345, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\C9_07.jpg")'},
//   {'index': 346, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\C9_08.jpg")'},
//   {'index': 347, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\C9_09.jpg")'},
//   {'index': 348, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\C9_10.jpg")'},
//   {'index': 349, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\C9_11.jpg")'},
//   {'index': 350, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\C9_12.jpg")'},
//   {'index': 351, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\C9_13.jpg")'},
//   {'index': 352, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\C9_14.jpg")'},
//   {'index': 353, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\C9_15.jpg")'},
//   {'index': 354, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\C9_16.jpg")'},
//   {'index': 355, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\C9_17.jpg")'},
//   {'index': 356, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\C9_18.jpg")'},
//   {'index': 357, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\C9_19.jpg")'},
//   {'index': 358, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\C9_20.jpg")'},
//   {'index': 359, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\C9_21.jpg")'},
//   {'index': 360, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\C9_22.jpg")'},
//   {'index': 361, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\C9_23.jpg")'},
//   {'index': 362, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\C9_24.jpg")'},
//   {'index': 363, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\C9_25.jpg")'},
//   {'index': 364, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\C9_26.jpg")'},
//   {'index': 365, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\C9_27.jpg")'},
//   {'index': 366, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\C9_28.jpg")'},
//   {'index': 367, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\C9_29.jpg")'},
//   {'index': 368, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\C9_30.jpg")'},
//   {'index': 369, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\C9_31.jpg")'},
//   {'index': 370, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\C9_32.jpg")'},
//   {'index': 371, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\C9_33.jpg")'},
//   {'index': 372, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\C9_34.jpg")'},
//   {'index': 373, 'category': 'non-target', 'image': 'require("C:\\Users\\kiddi\\OneDrive\\Documents\\Code\\behavirol_project\\src\\assets\\9\\C9_35.jpg")'},
// ]
